repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.1.1"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@latest"]
        description: "Format, organize imports, lint, and apply safe fixes to the committed files"

  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.6.0 # change to the latest version
    hooks:
      - id: oxlint
        verbose: true
